name: ncomp-dev
channels:
  - conda-forge
dependencies:
  - gcc_linux-64
  - gxx_linux-64
  - gfortran_linux-64
  - autoconf
  - autoconf-archive
  - automake
  - libtool
  - make
  - blas
  - liblapack
